// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.infrastructure.DatabaseContext;

#nullable disable

namespace ShoppingCart.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartAttributeModel", b =>
                {
                    b.Property<int>("CartAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttributeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeName")
                        .HasColumnType("TEXT");

                    b.Property<int>("CartProductGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceImpactAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartAttributeId");

                    b.HasIndex("CartProductGroupId");

                    b.ToTable("CartAttribute");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartModel", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("CartId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartProductGroupModel", b =>
                {
                    b.Property<int>("CartProductGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupAttributeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupAttributeName")
                        .HasColumnType("TEXT");

                    b.HasKey("CartProductGroupId");

                    b.HasIndex("CartProductId");

                    b.ToTable("CartProductGroup");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartProductModel", b =>
                {
                    b.Property<int>("CartProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartProductId");

                    b.HasIndex("CartId");

                    b.ToTable("CartProduct");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartAttributeModel", b =>
                {
                    b.HasOne("ShoppingCart.domain.Entities.ShoppingCart.CartProductGroupModel", "CartProductGroup")
                        .WithMany("Attributes")
                        .HasForeignKey("CartProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartProductGroup");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartProductGroupModel", b =>
                {
                    b.HasOne("ShoppingCart.domain.Entities.ShoppingCart.CartProductModel", "CartProduct")
                        .WithMany("ProductGroup")
                        .HasForeignKey("CartProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartProduct");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartProductModel", b =>
                {
                    b.HasOne("ShoppingCart.domain.Entities.ShoppingCart.CartModel", "Cart")
                        .WithMany("ListProduct")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartModel", b =>
                {
                    b.Navigation("ListProduct");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartProductGroupModel", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("ShoppingCart.domain.Entities.ShoppingCart.CartProductModel", b =>
                {
                    b.Navigation("ProductGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
